### ISSUE TITLE
Build an admin frontend for freesewing using vue.js and webpack

### ISSUE THREAD

**Issue by joostdecock** [freesewing/admin#1]
## First, a bit of history

Freesewing.org [is a JAMstack site](https://freesewing.org/blog/freesewing-goes-jamstack/). 
That means that it's a statically generated website (we use Jekyll for that) that uses JavaScript to make it do the dynamic stuff.

That JavaScript is currently a pile of jQuery code. And the mid-term plan is to port that code to vue.js and have something that is cleaner, easier to maintain, adapt, and extend.

## Why we're building an admin interface

Because we lack experienced vue.js developers, it seemed like a good idea to first get some vue.js experience under our belt without potentially wrecking the entire site. That's why I had this idea to build an admin interface first. This would allow us to remove the admin code from the frontend, making it leaner

In addition, it's a smaller and simpler project that allows us to get familiar with this new environment.

## The current plan

Sparked by my comment in [the February round-up blog post](https://freesewing.org/blog/roundup-2018-02/), myself and @alliejones briefly discussed this plan [in our Gitter chat room](https://gitter.im/freesewing/freesewing?at=5a98020d888332ee3ae7d330).

We're working on two repositories:

 - [admin](https://github.com/freesewing/admin): This repository, which will hold the admin frontend
 - [data](https://github.com/freesewing/data): The `admin` branch in the `data` repository will hold the admin backend

@alliejones has generously offered to help out, and since she has a bunch of frontend experience, she will get a minimal *hello world* up and running in this repository.

Meanwhile, @joostdecock will setup the backend in the [data](https://github.com/freesewing/admin-data) repo.

## What's needed?

Good question. I guess the first thing to do is to get a hello world page up and running.
Then, a login form, and some sort of session management so we can do authenticated stuff.

The data backend uses JSON web tokens for authentication. To login, you need to send a `POST` request to `/login` with the following parameters:

 - `login-email`
 - `login-password`

> **NOTE**
> The code in the `admin` branch of the data repository is no longer the same as the master branch. This means there are some differences. Specifically, the `/login` endpoint expects `email` and `password` as parameters, rather than `login-email` and `login-password`.

After that, well do admin stuff.
Perhaps a good starting point is a list of the *admin routes* in the current backend:

 - `POST` => `/admin/badge` : Adds a badge to a user profile
 - `DELETE` => `/admin/badge` : Removes a badge from a user profile
 - `PUT` => `/admin/password` : (Re)Sets a user password  
 - `PUT` => `/admin/birthday` : Sets a patron's birthday
 - `PUT` => `/admin/address` : Sets a patron's address
 - `POST` => `/admin/patron` : Sets the user's patron status
 - `POST` => `/admin/patron/email` : Sends out a patron *welcome email*
 - `GET` => `/admin/user/{handle}` : Loads a user account
 - `POST` => `/admin/errors/{hash:.*}` : Updates an error group

Notes:

 - Some of these will become irrelevant in the future (eg, we won't store patron address and birthday data online for GDRP compliance.
 - Some of these method/path combinations aren't exactly RESTful

## What's next?

That's how far we got. 
If you'd like to help out, join the discussion in the comments below, or stop by in [our gitter chat room](https://gitter.im/freesewing/freesewing).

**Comment by joostdecock** [comment]
Not sure what I was smoking 2 hours ago when I suggested to split up the backend too. That's clearly a bad idea as it would duplicate a bunch of code.

Instead, it might make more sense to group admin stuff in an admin controller. Currently admin methods are sprinkled over the regular controllers and that does irk me a bit.

So I'm thinking to not develop this in a seperate repo, but rather as a branch in [the data repository](https://github.com/freesewing/data/).

Which would also mean we can just name this repo `admin` 🤔

**Comment by joostdecock** [comment]
Ok, so I did rename this repo to **admin** and I've also setup a dedicated backend for it at [admin.data.freesewing.org](https://admin.data.freesewing.org).

There's a few things specific about this instance:

- Its CORS headers are set to `*` meaning that you can connect to the API from anywhere. This allows people check out this repo wherever they like and hook it up to a functional backend without having to set one up. Obviously, this is assuming that you are not working offline.
- Every push to the admin branch of [the data repository](https://github.com/freesewing/data) will trigger a new deploy **and** copy the production data. This way, you have real data to test with, but you can't accidentally cause any harm. For admin stuff, you'll need a freesewing account with the `admin` role though.

**Comment by joostdecock** [comment]
I've updated the backend to split up admin stuff into its own controller. The admin routes are now as such:

```
// Set new user password (by admin)
$app->put('/admin/user/{handle}/password', 'AdminController:userSetPassword');

// Add badge to user profile
$app->post('/admin/user/{handle}/badge/{badge}', 'AdminController:userAddBadge');

// Remove badge from user profile
$app->delete('/admin/user/{handle}/badge/{badge}', 'AdminController:userRemoveBadge');

// Set patron status in user profile
$app->put('/admin/user/{handle}/patron/{tier}', 'AdminController:userSetPatronTier');

// Send patron email
$app->post('/admin/user/{handle}/email/patron', 'AdminController:userSendPatronEmail');

// Load user account
$app->get('/admin/user/{handle}', 'AdminController:userLoad');

// Find users 
$app->get('/admin/find/users/{filter}', 'AdminController:userFind');

// Update error group
$app->post('/admin/errors/{hash:.*}', 'AdminController:errorUpdateGroup');
```

I've also created a `joost` branch here so I can much about a bit with things.

**Comment by alliejones** [comment]
@joostdecock I finally got a chance to take a proper look at your branch--I don't think there's any reason to replace what you've got with my boilerplate, you're already farther along anyway and it all seems like a solid setup to me!

The only weird thing I ran into is `yarn run build` failing on my machine on OSX. I think because of the `HOST` set in the `.env.development` file it tries to run the webserver on that host's IP instead of localhost.

**Comment by joostdecock** [comment]
Yeah, I wanted to show my work so far, and that was required to get the webpack dev server to listen on a public IP.

I should have kept it out of the repo, and furthermore it's no longer relevant as I now switched to proxying the webpack server through Apache.

It's running [here](https://joost.admin.freesewing.org) but it's in a terribly broken state as I'm updating the backend to encrypt the data at rest using libsodium.

**Comment by joostdecock** [comment]
Done for now. Everything works, albeit only with the `admin` branch of our data API because there's been some changed. 

Closing this to re-focus my attention on [our site repo](https://github.com/freesewing/site/)
